import Head from "next/head";

import { VStack } from "@chakra-ui/react";

import styles from "../../../styles/Home.module.css";

import CashCard from "../../../componets/Cards/cashcard";
import Header from "../../../componets/Navbars/header";
import News from "../../../componets/News/news";

const UsersHome = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <VStack>
          <CashCard />
          <News />
        </VStack>
      </main>
      <footer className={styles.footer}></footer>
    </>
  );
};

export default UsersHome;
