import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { VStack } from "@chakra-ui/react";

import { useUser, login, logout } from "../lib/auth";

import Header from "../componets/Navbars/header";
import CashCard from "../componets/Cards/cashcard";
import News from "../componets/News/news";

const Home: NextPage = () => {
  const user = useUser();

  const handleLogin = (): void => {
    login().catch((error) => console.error(error));
  };

  const handleLogout = (): void => {
    logout().catch((error) => console.error(error));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Auth Example</title>
      </Head>

      <div>
        <h1>Auth Example</h1>
        {user !== null ? (
          <>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
              <VStack>
                <CashCard />
                <News />
              </VStack>
            </main>
            <footer className={styles.footer}></footer>
          </>
        ) : (
          <h2>ログインしていない</h2>
        )}
        <button onClick={handleLogin}>ログイン</button>
        <button onClick={handleLogout}>ログアウト</button>
      </div>
    </div>
  );
};

export default Home;
